config:
  mcpClient:
    tools-file-system-directory: ./mcpFileSystemDirectory
    tools-sqlite-db-file: "./database.sqlite"
spring:
  ai:
    #Chat Model configuration
    openai:
      #TODO: OpenRouter: Unified API Gateway (500+ LLMs), ability to use routing models
      base-url: https://openrouter.ai/api/
      api-key: ${OPEN_ROUTER_API_KEY} # Always use env
      chat:
        options:
          model: openai/gpt-5.4-mini
          temperature: 0.2 # TODO: Explain temperature
          #TODO: Explain tokens & limits
          max-completion-tokens: 1000